version: '3'
services:
  db:
    image: mysql
    restart: always
    env_file:
      - ./.env 
    # volumes:
    #   - mysql:/var/lib/mysql

  node_server:
    container_name: node_container1
    build: .
    ports:
      - 4000:4000
    env_file:
      - ./.env
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# volumes:
#   mysql:    